import { NextResponse } from "next/server";
import { validatePlanRequest } from "@/lib/learning-engine";
import { runLearningAgentChain } from "@/lib/ai-chain";

export async function POST(request: Request) {
  let body: unknown;

  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body." }, { status: 400 });
  }

  const parsed = validatePlanRequest(body);

  if (!parsed.ok) {
    return NextResponse.json({ error: parsed.error }, { status: 400 });
  }

  const result = await runLearningAgentChain(parsed.value);

  return NextResponse.json({
    ...result,
    note:
      result.mode === "live-model"
        ? "Generated with a server-side model adapter. API keys were never sent to the browser."
        : "Generated by the local planner fallback. Add provider keys to enable live model calls."
  });
}
