import { NextResponse } from "next/server";
import { isDatabaseConfigured, saveLearningPlan } from "@/lib/db";
import { validatePlanRequest } from "@/lib/learning-engine";
import { runLearningAgentChain } from "@/lib/ai-chain";

export async function POST(request: Request) {
  let body: unknown;

  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body." }, { status: 400 });
  }

  const parsed = validatePlanRequest(body);

  if (!parsed.ok) {
    return NextResponse.json({ error: parsed.error }, { status: 400 });
  }

  const result = await runLearningAgentChain(parsed.value);
  let storedPlanId: string | null = null;
  let database: "saved" | "not-configured" | "error" = isDatabaseConfigured() ? "error" : "not-configured";

  if (isDatabaseConfigured()) {
    try {
      const stored = await saveLearningPlan(parsed.value, result.plan, result.mode);
      storedPlanId = stored.id;
      database = "saved";
    } catch {
      database = "error";
    }
  }

  return NextResponse.json({
    ...result,
    storedPlanId,
    database,
    note:
      result.mode === "live-model"
        ? "Generated with a server-side model adapter. API keys were never sent to the browser."
        : "Generated by the local planner fallback. Add provider keys to enable live model calls."
  });
}
